package main

import "fmt"

func genericHelper(plat Platform) string {
	if plat == PlatformMacOS {
		return "osxkeychain"
	}
	return "cache"
}

func RenderConfigLocal(email string, plat Platform) string {
	return fmt.Sprintf(`# Generated by dotctl. Machine-specific manual overrides go in config.machine.
[user]
	email = %s
[credential]
	helper = %s
[credential "https://github.com"]
	helper =
	helper = !gh auth git-credential
`, email, genericHelper(plat))
}
